### PR TITLE
Rename files to use two digits in the numbers

### PR DESCRIPTION
**Pull request by scottalthoff**
This way the files will be sorted in the file viewer.
I also removed a typo in Legal Information.

### CODE REVIEW

**Comment by sciencefish** [comment]
This renaming breaks the internal numbering relationships and the Pandoc assembly scripts

**Comment by scottalthoff** [comment]
Is there a way to edit these files to be sorted in the file view

**Comment by sciencefish** [comment]
> Is there a way to edit these files to be sorted in the file view?

I mirror the repository using the github desktop app and view it locally using Atom. Atom neatly organises it in "order" or I Just use the md file in QuestWorlds/markdown/. There's no reason to change the file names as they are the section headers in the final file. 
Screenshot 2021-02-07 at 15 53 15

**Comment by iancooper** [comment]
Thanks for trying this @scottalthoff It is worth noting that are contribution guidelines suggest raising an issue first, so that we know what you intend to change and can advise against you taking the time and effort to do that if we don't think it is something we are likely to approve.

I'll pick up on the separate issue

**Pull request closed without merging**
